In [1]:
from sklearn.datasets import load_diabetes

In [6]:
load=load_diabetes()

In [4]:
import pandas as pd

In [7]:
load

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [8]:
load.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [11]:
load['data'][0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613])

In [12]:
pd.DataFrame(load['data'])

0         1         2         3         4         5         6  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

            7         8         9  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [13]:
load['target']

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [14]:
load['DESCR']

'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, total serum cholesterol\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, total cholesterol / HDL\n      - s5      ltg, possibly log of serum triglycerides level\n      - s6      glu, blood sugar

In [17]:
load['feature_names']

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [19]:
load['frame']

In [21]:
load['data'][0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613])

In [22]:
pd.DataFrame(load['data'][0])

0
0  0.038076
1  0.050680
2  0.061696
3  0.021872
4 -0.044223
5 -0.034821
6 -0.043401
7 -0.002592
8  0.019907
9 -0.017646

In [23]:
load['data']

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [24]:
load['data'].shape

(442, 10)

In [26]:
load['data'][0].shape

(10,)

In [52]:
X=pd.DataFrame(load['data'],columns=load['feature_names'])
X

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [30]:
y=load['target']
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report,precision_score,f1_score,recall_score
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

In [63]:
X_train

age       sex       bmi        bp        s1        s2        s3  \
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
359  0.038076  0.050680  0.005650  0.032201  0.006687  0.017475 -0.024993   
248 -0.041840 -0.044642  0.047685  0.059744  0.127771  0.128016 -0.024993   
149 -0.049105  0.050680 -0.005128 -0.046985 -0.020832 -0.020416 -0.069172   
285  0.012648 -0.044642 -0.020218 -0.015999  0.012191  0.021233 -0.076536   
..        ...       ...       ...       ...       ...       ...       ...   
123  0.005383  0.050680  0.034751 -0.001091  0.152538  0.198788 -0.061809   
68   0.038076  0.050680 -0.029918 -0.040099 -0.033216 -0.024174 -0.010266   
113  0.019913  0.050680  0.014272  0.063187  0.014942  0.020293 -0.047082   
108  0.019913  0.050680  0.045529  0.029894 -0.062111 -0.055802 -0.072854   
384  0.034443  0.050680 -0.029918  0.004658  0.093372  0.086994  0.033914   

           s4        s5        s6  
4   -0.002592 -0.031988 -0.046641  
359  0.034309  0.014821  0.061054  
248  0.108111  0.063890  0.040343  
149  0.071210  0.061238 -0.038357  
285  0.108111  0.059879 -0.021788  
..        ...       ...       ...  
123  0.185234  0.015568  0.073480  
68  -0.002592 -0.012909  0.003064  
113  0.034309  0.046662  0.090049  
108  0.026929  0.045604  0.040343  
384 -0.002592  0.024055 -0.038357  

[353 rows x 10 columns]

In [64]:
X_test

age       sex       bmi        bp        s1        s2        s3  \
185 -0.074533  0.050680 -0.018062  0.008101 -0.019456 -0.024800 -0.065491   
109  0.038076  0.050680 -0.009439  0.002351  0.001183  0.037517 -0.054446   
241  0.030811  0.050680 -0.008362  0.004658  0.014942  0.027496  0.008142   
163  0.016281  0.050680  0.072474  0.076958 -0.008449  0.005575 -0.006584   
41  -0.099961 -0.044642 -0.067641 -0.108956 -0.074494 -0.072712  0.015505   
..        ...       ...       ...       ...       ...       ...       ...   
40   0.005383  0.050680 -0.008362  0.021872  0.054845  0.073215 -0.024993   
46  -0.056370 -0.044642 -0.011595 -0.033213 -0.046975 -0.047660  0.004460   
102 -0.092695 -0.044642  0.028284 -0.015999  0.036958  0.024991  0.056003   
71  -0.001882 -0.044642  0.033673  0.125158  0.024574  0.026243 -0.010266   
57  -0.027310 -0.044642 -0.063330 -0.050427 -0.089630 -0.104340  0.052322   

           s4        s5        s6  
185  0.034309  0.067318 -0.017646  
109  0.050176 -0.025953  0.106617  
241 -0.008127 -0.029526  0.056912  
163 -0.002592 -0.023647  0.061054  
41  -0.039493 -0.049872 -0.009362  
..        ...       ...       ...  
40   0.034309  0.012551  0.094191  
46  -0.039493 -0.007977 -0.088062  
102 -0.039493 -0.005142 -0.001078  
71  -0.002592  0.026717  0.061054  
57  -0.076395 -0.056153 -0.067351  

[89 rows x 10 columns]

In [65]:
len(X_train) + len(X_test)

442

In [66]:
len(X_test)

89

In [67]:
len(X_train)

353

In [68]:
model=LogisticRegression()

In [69]:
model.fit(X_train,y_train)

LogisticRegression()

In [71]:
model.score(X_test,y_test)

0.0

In [53]:
from sklearn.linear_model import LinearRegression

In [72]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [73]:
X_train

age       sex       bmi        bp        s1        s2        s3  \
17   0.070769  0.050680  0.012117  0.056301  0.034206  0.049416 -0.039719   
66  -0.009147  0.050680 -0.018062 -0.033213 -0.020832  0.012152 -0.072854   
137  0.005383 -0.044642  0.049840  0.097615 -0.015328 -0.016345 -0.006584   
245 -0.027310 -0.044642 -0.035307 -0.029770 -0.056607 -0.058620  0.030232   
31  -0.023677 -0.044642 -0.065486 -0.081413 -0.038720 -0.053610  0.059685   
..        ...       ...       ...       ...       ...       ...       ...   
106 -0.096328 -0.044642 -0.076264 -0.043542 -0.045599 -0.034821  0.008142   
270  0.005383  0.050680  0.030440  0.083844 -0.037344 -0.047347  0.015505   
348  0.030811 -0.044642 -0.020218 -0.005670 -0.004321 -0.029497  0.078093   
435 -0.012780 -0.044642 -0.023451 -0.040099 -0.016704  0.004636 -0.017629   
102 -0.092695 -0.044642  0.028284 -0.015999  0.036958  0.024991  0.056003   

           s4        s5        s6  
17   0.034309  0.027364 -0.001078  
66   0.071210  0.000272  0.019633  
137 -0.002592  0.017036 -0.013504  
245 -0.039493 -0.049872 -0.129483  
31  -0.076395 -0.037129 -0.042499  
..        ...       ...       ...  
106 -0.039493 -0.059471 -0.083920  
270 -0.039493  0.008641  0.015491  
348 -0.039493 -0.010903 -0.001078  
435 -0.002592 -0.038460 -0.038357  
102 -0.039493 -0.005142 -0.001078  

[353 rows x 10 columns]

In [74]:
y_train

array([144., 150., 280., 125.,  59.,  65., 281., 277., 167.,  90.,  72.,
       178.,  88., 270., 101., 197.,  97.,  53.,  71., 262.,  52., 102.,
       166., 189., 173., 220., 206.,  97.,  60.,  61., 242., 121., 128.,
       104., 265., 132., 283., 174., 129., 257., 137.,  63.,  93., 232.,
       208., 261., 179., 258., 262.,  51., 237.,  71., 139., 268.,  69.,
       317., 249., 154., 192., 116.,  81., 122., 259., 191., 292.,  55.,
       107., 210.,  91., 253.,  85., 252.,  59.,  78., 200.,  78., 245.,
       175.,  42., 127.,  53.,  94., 104., 199., 265., 281., 248., 257.,
       215., 303., 170.,  59., 277., 209., 138., 198., 124.,  96., 288.,
       225., 265., 101.,  55., 198.,  51., 252.,  64., 220., 131., 212.,
       142., 103., 155., 121.,  86., 111.,  65., 131.,  51., 128., 141.,
        48., 109., 178.,  88.,  84., 216., 150.,  60.,  96., 190.,  74.,
       279., 182., 160., 245., 276., 174., 180., 150., 196., 138.,  97.,
       246., 321., 308., 109.,  69., 182., 258., 16

In [75]:
model1=LinearRegression()

In [76]:
model1.fit(X_train,y_train)

LinearRegression()

In [77]:
model1.score(X_test,y_test)

0.4526027629719196

In [89]:
X=pd.DataFrame(load['data'],columns=load['feature_names'])
X

for i in range(1000):
    given_random(i)
    
    
data={'Random':[],'Acuracy':[]}
def given_random(random_no):
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=random_no)
    model3= LinearRegression()
    model3.fit(X_train,y_train)
    y_pred=model3.predict(X_test)
    score=model3.score(X_test,y_test)
    
    data['Random'].append(random_no)
    data['Acuracy'].append(score)
    
    
    
    
    

NameError: name 'x' is not defined

In [86]:
for i in range(1000):
    given_random(i)
    

NameError: name 'x' is not defined

In [92]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas as pd

# Load the diabetes dataset
diabetes = load_diabetes()
X = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
y = diabetes.target

data = {'Random': [], 'Accuracy': []}

def given_random(random_no):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=random_no)
    model = LinearRegression()
    model.fit(X_train, y_train)
    score = model.score(X_test, y_test)
    data['Random'].append(i)
    data['Accuracy'].append(score)
#    return score

for i in range(1000):
    given_random(i)
#    score = given_random(i)
#    data['Random'].append(i)
#    data['Accuracy'].append(score)


# Convert data to DataFrame for easier analysis
#df = pd.DataFrame(data)
#print(df.head())
#print(data['Random'].append(i))
#print(data['Accuracy'].append(score))

In [93]:
pg=pd.DataFrame(data)

In [94]:
pg

Random  Accuracy
0         0  0.332233
1         1  0.438432
2         2  0.439934
3         3  0.416179
4         4  0.461099
..      ...       ...
995     995  0.514113
996     996  0.408921
997     997  0.530937
998     998  0.325679
999     999  0.607834

[1000 rows x 2 columns]

In [95]:
pg.max()

Random      999.000000
Accuracy      0.660809
dtype: float64

In [99]:
y_pred=model1.predict(X_test)

In [98]:
y_test

array([219.,  70., 202., 230., 111.,  84., 242., 272.,  94.,  96.,  94.,
       252.,  99., 297., 135.,  67., 295., 264., 170., 275., 310.,  64.,
       128., 232., 129., 118., 263.,  77.,  48., 107., 140., 113.,  90.,
       164., 180., 233.,  42.,  84., 172.,  63.,  48., 108., 156., 168.,
        90.,  52., 200.,  87.,  90., 258., 136., 158.,  69.,  72., 171.,
        95.,  72., 151., 168.,  60., 122.,  52., 187., 102., 214., 248.,
       181., 110., 140., 202., 101., 222., 281.,  61.,  89.,  91., 186.,
       220., 237., 233.,  68., 190.,  96.,  72., 153.,  98.,  37.,  63.,
       184.])

In [101]:
confusion_metrix(y_test,y_pred)

NameError: name 'confusion_metrix' is not defined